### ISSUE TITLE
[Enhancement] IconSize Property

### ISSUE THREAD

**Issue by mhrastegary77** [anpin/ContextMenuContainer#2]
## Summary
the icon size on iOS is really good but
as you can see the android version doesn't have text when an item has icon.
and size of the icon on macOS and UWP and Android is not looking good.

# Screenshot
![Screenshot (1222)](https://user-images.githubusercontent.com/42671084/119112190-16999c00-ba39-11eb-9e24-f46bf067ce6d.png)
![Screenshot (1224)](https://user-images.githubusercontent.com/42671084/119112196-18fbf600-ba39-11eb-966d-46d6144ead99.png)

**Comment by anpin** [comment]
Hi @mhrastegary77 thanks for your interest and feedback! This is still pretty much in beta and I'm sorry you got such a result. I should say it worked for my case with the icons, but I had them only in menus with a single row. Which size of the icon did you used on UWP?

**Comment by mhrastegary77** [comment]
Hi Pavel first of all you have a really nice work here i love this package!!!
and i used a shared 513*513 image with [ResizetizerNT](https://github.com/Redth/ResizetizerNT) on all of my platforms.

**Comment by anpin** [comment]
I think it could be a problem with the ResizetizerNT as I'm testing it with SVG or pre rendered PNGs for all DPI and it looks fine. Looking at the  ResizetizerNT docs it seems that you have to specify size request for the XF Image in order for it to work, but I don't use XF image for icons here, it is handled directly in the platform implementation (so you just bind FileImageSource, not the actual Image). I guess as a workaround you can try to specify a native Image using same asset somewhere outside of ContextMenuItem, so  ResizetizerNT  will handle it properly.

**Comment by mhrastegary77** [comment]
Hmm yeah you were right!!! Once I set a baseSize like 20 for my images it looks fine on UWP and Android now too but still on the Android only the first item has icon and others doesn't have any.

**Comment by anpin** [comment]
Can you post a sample of how you reference icons? On screenshots in the first post I can see icons only on the first item for all four platforms

**Comment by mhrastegary77** [comment]
in the screenshot it is one icon! And in one of my projects I just seeing Android doesn't have the second icon but others like iOS and UWP are fine

![image](https://user-images.githubusercontent.com/42671084/119870741-8d6de380-bed6-11eb-8fab-4b8318f01191.png)

**Comment by anpin** [comment]
In the provided sample it has multiple icons on Android. If you can post a repro where it doesn't show multiple icons on Android I can further investigate it. Otherwise I suggest you check that your icons have proper names on Android and they are located in the drawable folder.

**Comment by mhrastegary77** [comment]
yup! you were right my icons should be located in the drawable folder cant't use more than one shared image on android, it's fixed thanks.
