### ISSUE TITLE
How do we use this?

### ISSUE THREAD

**Issue by rezamohamed** [anpin/ContextMenuContainer#4]
The code here doesn't load in VS (src folder, just looking for iOS and Droid). So how do you use this in an application?

<img width="396" alt="Screen Shot 2021-06-06 at 8 52 00 PM" src="https://user-images.githubusercontent.com/18199852/120949007-1a037780-c709-11eb-8f00-1b1fd85d1575.png">

**Comment by anpin** [comment]
Hi, it certainly loads on mine. Which version do you use and is there any error in particular? Regarding the way to use, you can install nuget into your projects and then follow  the readme. 

>

**Comment by rezamohamed** [comment]
I just downloaded the code from here and tried to open the solution and it fails with the error that's on the screenshot. I didn't realize it was on nuget and it seems to, almost, work. I'm trying to use it in a CarouselView, it doesn't quite function. I attached a small sample if you wanna check it out,
[TestSfListView.zip](https://github.com/anpin/ContextMenuContainer/files/6605591/TestSfListView.zip)
 please.

**Comment by anpin** [comment]
@rezamohamed sorry haven't seen the screenshot in the email client. I guess you need the MSBuild.Sdk.Extras installed on mac somehow as the error suggests, but I'm building it on Windows  so not sure if it is viable. I'll check you repro later this week.

**Comment by rezamohamed** [comment]
The issue is that on the CarouselView, the first CarouselItem is displayed in the background.
<img width="208" alt="Screen Shot 2021-06-07 at 12 52 35 PM" src="https://user-images.githubusercontent.com/18199852/121066388-701afe00-c78f-11eb-88d6-a985a71a6c96.png">

And the CommandParameter sends an Object of the entire Carousel collection and not the currently focused one.

**Comment by anpin** [comment]
I think you should use it inside your DataTemplate so it will be attached to your content view inside of the swipe view.

>

**Comment by rezamohamed** [comment]
yep! that was it! thanks, looks to be working like a charm now.

**Comment by rezamohamed** [comment]
Pavel, from the context actions, can I execute a codebehind event rather than a viewmodel command and also pass the command parameter to the codebehind event?

**Comment by rezamohamed** [comment]
I'm on v1.0.5, I don't see Invoked. Screenshot below.

![Uploading Screen Shot 2021-06-08 at 10.28.52 AM.png…]()

**Comment by anpin** [comment]
right, because it is a method, not a property

**Comment by rezamohamed** [comment]
I'm not following. My question is I have the Contextmenu in Carousel.xaml, and I have an event in Carousel.xaml.cs that I want to trigger when the user clicks ContextMenu. The Command triggers a command in the ViewModel, How would I invoke an event in the codebehind? 

With the InvokeCommand you mentioned above, I guess I am unclear how to use it.

**Comment by anpin** [comment]
I see what you mean. There is no event at this point.

>

**Comment by rezamohamed** [comment]
Any chance of adding it please? just a way to trigger an event, and send the parameters to the event via CommandParameter. It would make the component fully usable at that point.

**Comment by anpin** [comment]
It is totally feasible to add the event in my opinion, so will look into it 

>

**Comment by rezamohamed** [comment]
Appreciate that, will keep an eye out for a new version. This component fills a big gap, in my opinion, especially for Carousel where the swipe methods for actions are limited. Great work.

**Comment by anpin** [comment]
> 
> 
> Appreciate that, will keep an eye out for a new version. This component fills a big gap, in my opinion, especially for Carousel where the swipe methods for actions are limited. Great work.

Please find version 1.0.6 on nuget with the event added

**Comment by rezamohamed** [comment]
ItemTapped event works, but the EventArgs is not working. My expectation was that the EventArgs would populate whatever is defined in the CommandParameter...but this isn't working. The CommandParameter does work for the Command however.

**Comment by anpin** [comment]
You can access it via sender in the event handler. Please refer to the test project for example.

>

**Comment by rezamohamed** [comment]
I do see it now, in the BindingContext of the ContextMenuItem that is returned via sender. Is that what you are referring to? I would have to drill down to get that info, usually it would just be sent via EventArgs, so it was different. Can you confirm, please?

        private void CarouselDelete_OnItemTapped(object sender, EventArgs e)
        {
            var x = (ContextMenuItem) sender;
            var y = x.BindingContext;
        }

<img width="755" alt="Screen Shot 2021-06-11 at 12 31 01 AM" src="https://user-images.githubusercontent.com/18199852/121635712-522df180-ca4c-11eb-8a0a-37c3c5c890b3.png">

x, y:

<img width="767" alt="Screen Shot 2021-06-11 at 12 31 35 AM" src="https://user-images.githubusercontent.com/18199852/121635746-670a8500-ca4c-11eb-9bfc-026a85b3ed82.png">

**Comment by anpin** [comment]
If bind or set value of the CommandParameter you should be able to access it as x.CommandParameter 

>

**Comment by rezamohamed** [comment]
yep! I see it now. Works perfectly. Thanks
